server:
  port: 8080
spring:
  application:
    name: eureka

eureka:
  instance:
    # 是否使用IP地址
    prefer-ip-address: true
    #instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${HOST_NAME}
    status-page-url-path: ${server.servletPath}/info
    health-check-url-path: ${server.servletPath}/health
  client:
    healthcheck:
      # 健康检查
      enabled: true
    serviceUrl:
      # eureka注册中心地址
      defaultZone: http://${spring.cloud.client.ip-address}:${server.port}/eureka
    # 是否注册自身
    fetch-registry: true
    # 只允许访问别人，不让其他服务访问自己
    register-with-eureka: true
    root'@'localhost' IDENTIFIED BY 'ting_root';

  Gm&+=5hEQpP4