server:
  port: 8083
spring:
  application:
    name: client
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8080/eureka

